# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba5bcd8b2d0ddf1fdbfe372ee1140c4a9dfd640c4877011a45e3b0b37c0c235b916234180db4b72486d55a2effbb3a63be12933a82c6942da5c37957be8bf91

test:
  secret_key_base: fb3bfbaa38e7164a26e2553f0a88e879d2e47b2641d132ce83a7ece718c33f8df081c41c79b7da811165592ede6db4e58c91ecc72de1695883dfd6b59b04fc96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
